### ISSUE TITLE
Investigate migrating from mftrace to mf2p1

### ISSUE THREAD

**Issue by k4b7** [Khan/MathJax-dev#5]
@gagern posted the following in https://github.com/Khan/KaTeX/pull/614#issuecomment-274124941:
> http://stackoverflow.com/questions/20384088/script-for-metafont-to-ttf-conversion suggested `md2pt1` as an alternative to `mftrace`. Sounds reasonable to me. The way I see it, both are perl scripts that call `mf` resp. `mpost` at some point, so the same patch to make the font a bit blacker should be applicable there as well. I see lillypond [switched from `mftrace` to `mf2pt1`](https://github.com/lilypond/lilypond/commit/37dd6278153b188ba59c4c58ff90540c4d7d69ad) in 2008, perhaps we can learn something from that.

http://www.ctan.org/pkg/mf2pt1

**Comment by gagern** [comment]
Superseded by #6 which has a lot more detail.
